version: '3.4'

services:
  pwa:
    image: gcr.io/racoo-248604/pwa:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: pwa
    hostname: localhost
    expose:
      - 80
    ports:
      - 8081:80

